spring:
  # static
  resources:
    add-mappings: true
    cache:
      cachecontrol:
        max-age: 3600
    chain:
      cache: true
      enabled: true
      compressed: true
    static-locations: classpath:/static

  thymeleaf:
    # stop cache
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
#    password: root
    hikari:
      pool-name: DateHikariCP
      minimum-idle: 5
      idle-timeout: 1800000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  redis:
    #    host:
    port: 6379
    database: 0
    connect-timeout: 10000ms
    lettuce:
      pool:
        # default 8
        max-active: 8
        # default -1
        max-wait: 10000ms
        # default 8
        max-idle: 200
        # default 0
        min-idle: 5

mybatis_plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.practice.seckill.pojo

logging:
  level:
    com.practice.seckill.mapper: debug

rabbitmq:
  host: localhost
  username: guest
  password: guest
  virtual-host: /
  port: 5672
  listener:
    simple:
      concurrency: 10
      max-concurrency: 10
      prefetch: 1
      auto-startup: true
      default-requeue-rejected: true
  template:
    retry:
      enabled: true
      initial-interval: 1000ms
      max-attempts: 3
      max-interval: 10000ms
      multiplier: 1

